"use client";

import { useState } from "react";

const projects = [
  { title: "Pulse Analytics", category: "Data Science · 2025", description: "Plateforme d'analyse prédictive pour piloter la performance commerciale.", tech: "Python · Pandas · Scikit-learn · Next.js", color: "#d5f45b", visual: "◒" },
  { title: "Kivu Vision", category: "Computer Vision · 2024", description: "Détection intelligente et classification d'images pour une chaîne logistique.", tech: "Python · PyTorch · OpenCV · FastAPI", color: "#ed704b", visual: "✳" },
  { title: "AfriMarket", category: "Web application · 2024", description: "Expérience e-commerce rapide et accessible pensée pour le mobile.", tech: "TypeScript · React · PostgreSQL · Prisma", color: "#c5d5e8", visual: "⌁" },
];

const skills = ["Python", "SQL", "Pandas", "Scikit-learn", "TensorFlow", "PyTorch", "FastAPI", "TypeScript", "React", "Next.js", "PostgreSQL", "Docker"];

export default function Home() {
  const [filter, setFilter] = useState("Tous");
  const [sent, setSent] = useState(false);

  return (
    <main>
      <header className="fixed top-0 z-20 flex w-full items-center justify-between border-b border-[var(--line)] bg-[rgba(244,241,235,.92)] px-5 py-4 backdrop-blur-md md:px-10">
        <a href="#top" className="mono text-sm tracking-[-.04em]">EK<span className="text-[var(--orange)]">.</span></a>
        <nav className="hidden gap-6 text-[11px] uppercase tracking-[.12em] md:flex"><a href="#about">À propos</a><a href="#skills">Compétences</a><a href="#services">Services</a><a href="#projects">Projets</a><a href="#journey">Parcours</a><a href="#blog">Blog</a><a href="#contact">Contact</a></nav>
        <a href="/admin" className="rounded-full border border-[var(--ink)] px-4 py-2 text-xs font-semibold transition-colors hover:bg-[var(--ink)] hover:text-[var(--background)]">Espace admin ↗</a>
      </header>

      <section id="top" className="grid-paper relative flex min-h-screen flex-col justify-end overflow-hidden px-5 pb-14 pt-32 md:px-10 md:pb-20">
        <div className="absolute right-[10%] top-[26%] hidden h-36 w-36 rotate-12 border border-[var(--ink)] md:block"><div className="absolute inset-4 border border-[var(--orange)]" /></div>
        <div className="max-w-6xl reveal"><p className="mono mb-5 text-xs uppercase tracking-[.18em] text-[var(--muted)]">Kinshasa · RDC / développeur freelance</p><h1 className="display max-w-6xl text-[clamp(3.4rem,9vw,9rem)] leading-[.86] tracking-[-.06em]">Je transforme les<br /><em className="text-[var(--orange)]">données</em> en impact.</h1><div className="mt-10 flex max-w-xl items-start justify-between gap-8 text-sm leading-6 text-[var(--muted)] md:ml-[34%]"><p>Je suis <strong className="text-[var(--ink)]">Excellence Kisengo</strong>, développeur freelance spécialisé en Data Science, Machine Learning, Intelligence Artificielle et développement web.</p><span className="mono hidden text-xs text-[var(--ink)] md:block">↓<br />défiler</span></div></div>
        <div className="absolute bottom-5 left-0 w-[200%] overflow-hidden border-y border-[var(--line)] py-3 text-xs uppercase tracking-[.16em] text-[var(--muted)]"><div className="marquee flex w-max gap-10">Data Science — Machine Learning — Artificial Intelligence — Web Development — Data Science — Machine Learning —</div></div>
      </section>

      <section id="about" className="px-5 py-24 md:px-10 md:py-32"><div className="grid gap-12 md:grid-cols-[.8fr_1.2fr]"><div><p className="mono mb-5 text-xs text-[var(--orange)]">01 / À propos</p><h2 className="display text-5xl leading-[.9] md:text-7xl">La tech au<br /><em>service du réel.</em></h2></div><div className="max-w-xl text-sm leading-7 text-[var(--muted)]"><p>Je conçois des solutions numériques utiles, de l'exploration d'un jeu de données jusqu'à la mise en production d'une application complète. Mon approche combine rigueur technique, compréhension métier et attention portée à l'expérience utilisateur.</p><p className="mt-6 text-[var(--ink)]">Disponible pour des missions freelance, collaborations et projets à impact.</p></div></div></section>

      <section id="skills" className="bg-[var(--ink)] px-5 py-24 text-[var(--background)] md:px-10 md:py-32"><div className="grid gap-12 md:grid-cols-[.8fr_1.2fr]"><div><p className="mono mb-5 text-xs text-[var(--accent)]">02 / Compétences</p><h2 className="display text-5xl leading-none md:text-7xl">Boîte à<br /><em className="text-[var(--accent)]">outils.</em></h2></div><div className="grid grid-cols-2 gap-x-8 gap-y-3 border-t border-[#4b4c46] pt-5 text-sm sm:grid-cols-3">{skills.map((skill) => <span key={skill} className="border-b border-[#4b4c46] py-3 text-[#c4c5bd]">{skill}</span>)}</div></div></section>

      <section id="services" className="px-5 py-24 md:px-10 md:py-32"><div className="mb-12 border-b border-[var(--line)] pb-5"><p className="mono mb-3 text-xs text-[var(--orange)]">03 / Services</p><h2 className="display text-5xl md:text-7xl">Ce que je peux<br />construire avec vous.</h2></div><div className="grid gap-0 md:grid-cols-4">{[["01", "Data Science", "Analyse exploratoire, visualisation et modèles statistiques pour éclairer vos décisions."], ["02", "Machine Learning", "Modèles prédictifs, NLP et computer vision, de l'expérimentation au déploiement."], ["03", "Intelligence Artificielle", "Intégration d'IA générative et automatisation de workflows dans vos produits."], ["04", "Développement web", "Applications web robustes, rapides et scalables avec les technologies modernes."]].map(([n, title, text]) => <article key={n} className="border-b border-[var(--line)] p-5 first:border-l-0 md:border-l md:border-b-0 md:first:pl-0"><span className="mono text-xs text-[var(--orange)]">{n}</span><h3 className="mt-16 text-xl font-semibold">{title}</h3><p className="mt-4 text-sm leading-6 text-[var(--muted)]">{text}</p></article>)}</div></section>

      <section id="projects" className="px-5 py-24 md:px-10 md:py-32"><div className="mb-10 flex items-end justify-between border-b border-[var(--line)] pb-5"><div><p className="mono mb-3 text-xs text-[var(--orange)]">04 / Projets</p><h2 className="display text-5xl md:text-7xl">Projets sélectionnés</h2></div><span className="mono text-xs text-[var(--muted)]">{projects.length} études de cas</span></div><div className="mb-8 flex gap-2">{["Tous", "Data", "Web"].map((item) => <button key={item} onClick={() => setFilter(item)} className={`rounded-full px-4 py-2 text-xs ${filter === item ? "bg-[var(--ink)] text-[var(--background)]" : "border border-[var(--line)]"}`}>{item}</button>)}</div><div className="grid gap-5 md:grid-cols-3">{projects.map((project, index) => <article key={project.title} className={`group ${filter === "Web" && index < 2 ? "hidden" : filter === "Data" && index === 2 ? "hidden" : ""}`}><div style={{ backgroundColor: project.color }} className="relative flex aspect-[4/3] items-center justify-center overflow-hidden border border-[var(--ink)]"><span className="display text-[9rem] transition-transform duration-500 group-hover:scale-110">{project.visual}</span><span className="absolute bottom-4 left-4 mono text-xs">0{index + 1}</span></div><div className="border-b border-[var(--line)] py-4"><div className="flex justify-between"><h3 className="text-lg font-semibold">{project.title}</h3><span>↗</span></div><p className="mt-1 text-xs text-[var(--orange)]">{project.category}</p><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{project.description}</p><p className="mono mt-4 text-[10px] text-[var(--ink)]">{project.tech}</p></div></article>)}</div></section>

      <section id="journey" className="bg-[#e6e1d8] px-5 py-24 md:px-10 md:py-32"><div className="grid gap-12 md:grid-cols-[.8fr_1.2fr]"><div><p className="mono mb-5 text-xs text-[var(--orange)]">05 / Expériences</p><h2 className="display text-5xl leading-none md:text-7xl">Mon<br /><em>parcours.</em></h2></div><div className="divide-y divide-[var(--line)]">{[["2024 — aujourd'hui", "Développeur freelance", "Accompagnement de startups et entreprises dans leurs projets data, IA et web."], ["2022 — 2024", "Data & IA", "Projets d'analyse, modélisation prédictive et automatisation de processus."], ["2019 — 2022", "Formation technique", "Développement logiciel, bases de données et fondations en intelligence artificielle."]].map(([date, title, text]) => <div key={date} className="grid gap-2 py-6 md:grid-cols-[150px_1fr]"><span className="mono text-xs text-[var(--orange)]">{date}</span><div><h3 className="font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{text}</p></div></div>)}</div></div></section>

      <section id="blog" className="px-5 py-24 md:px-10 md:py-32"><div className="mb-10 border-b border-[var(--line)] pb-5"><p className="mono mb-3 text-xs text-[var(--orange)]">06 / Blog</p><h2 className="display text-5xl md:text-7xl">Notes & réflexions</h2></div><div className="divide-y divide-[var(--line)]">{[["01", "Pourquoi les données racontent toujours une histoire", "Data Science · 8 min"], ["02", "Construire une API ML prête pour la production", "Machine Learning · 10 min"], ["03", "L'IA générative comme outil, pas comme produit", "Intelligence Artificielle · 6 min"]].map(([n, title, meta]) => <a href="#blog" key={n} className="grid grid-cols-[44px_1fr_auto] items-center gap-5 py-6 transition-colors hover:bg-[var(--accent)] md:grid-cols-[80px_1fr_auto]"><span className="mono text-xs text-[var(--muted)]">{n}</span><h3 className="text-lg md:text-2xl">{title}</h3><span className="mono text-[10px] text-[var(--muted)]">{meta}</span></a>)}</div></section>

      <section id="testimonials" className="bg-[var(--accent)] px-5 py-24 md:px-10 md:py-32"><p className="mono mb-5 text-xs">07 / Témoignages</p><blockquote className="display max-w-5xl text-4xl leading-[.95] md:text-7xl">“Excellence sait rendre simple ce qui semblait complexe. Une vraie capacité à comprendre le besoin et à livrer une solution qui fonctionne.”</blockquote><p className="mt-8 text-sm">— Client freelance, projet data</p></section>

      <section id="contact" className="bg-[var(--ink)] px-5 py-24 text-[var(--background)] md:px-10 md:py-32"><div className="grid gap-14 md:grid-cols-[1fr_1fr]"><div><p className="mono mb-5 text-xs text-[var(--accent)]">08 / Contact</p><h2 className="display text-6xl leading-[.9] md:text-8xl">Un projet<br /><em className="text-[var(--accent)]">en tête ?</em></h2><div className="mt-12 space-y-3 text-sm text-[#b1b2aa]"><a className="block hover:text-white" href="mailto:excellencekisengo000@gmail.com">excellencekisengo000@gmail.com ↗</a><a className="block hover:text-white" href="https://github.com/Exkis" target="_blank" rel="noreferrer">GitHub ↗</a><a className="block hover:text-white" href="https://www.linkedin.com" target="_blank" rel="noreferrer">LinkedIn ↗</a><a className="block hover:text-white" href="https://wa.me/?text=Bonjour%20Excellence%2C%20je%20souhaite%20parler%20d%27un%20projet." target="_blank" rel="noreferrer">WhatsApp ↗</a></div></div><form className="space-y-5" onSubmit={async (event) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const response = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: data.get("name"), email: data.get("email"), message: data.get("message") }) }); if (response.ok) { form.reset(); setSent(true); } }}><label className="block text-xs uppercase tracking-[.12em] text-[#b1b2aa]">Nom<input name="name" required className="mt-2 w-full border-b border-[#55564f] bg-transparent py-3 outline-none focus:border-[var(--accent)]" /></label><label className="block text-xs uppercase tracking-[.12em] text-[#b1b2aa]">Email<input name="email" required type="email" className="mt-2 w-full border-b border-[#55564f] bg-transparent py-3 outline-none focus:border-[var(--accent)]" /></label><label className="block text-xs uppercase tracking-[.12em] text-[#b1b2aa]">Votre message<textarea name="message" required rows={4} className="mt-2 w-full resize-none border-b border-[#55564f] bg-transparent py-3 outline-none focus:border-[var(--accent)]" /></label><button className="bg-[var(--accent)] px-6 py-4 text-sm text-[var(--ink)]">{sent ? "Message envoyé ✓" : "Envoyer le message ↗"}</button></form></div></section>
      <footer className="border-t border-[#4b4c46] bg-[var(--ink)] px-5 py-8 text-xs text-[#b1b2aa] md:px-10"><div className="flex justify-between"><span>© 2026 Excellence Kisengo</span><a href="#top">Retour en haut ↑</a></div></footer>
    </main>
  );
}
